import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // callsSidebar: [{ type: 'autogenerated', dirName: '.' }],

  callsSidebar: [
    {
      type: 'category',
      label: 'Call',
      link: {
        'type': 'generated-index',
      },
      items: [
        'calls/overture',
        'calls/nogizakanouta',
        {
          type: 'category',
          label: '36th チートデイ',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/36/cheat-day',
            'singles/36/otoshimono'
          ]
        },
        {
          type: 'category',
          label: '35th チャンスは平等',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/35/chancewabyoudo'
          ]
        },
        {
          type: 'category',
          label: '34th Monopoly',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/34/monopoly'
          ]
        },
        {
          type: 'category',
          label: '33rd おひとりさま天国',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/33/ohitorisamatengoku'
          ]
        },
        {
          type: 'category',
          label: '32nd 人は夢を二度見る',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/32/hitowayumeonidomiru'
          ]
        },
        {
          type: 'category',
          label: '31st ここにはないもの',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/31/kokoniwanaimono'
          ]
        },
        {
          type: 'category',
          label: '30th 好きというのはロックだぜ',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/30/sukitoiunowarockdaze'
          ]
        },
        {
          type: 'category',
          label: '29th Actually',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/29/actually'
          ]
        },
        {
          type: 'category',
          label: '28th 君に叱られた',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/28/kiminishikarareta'
          ]
        },

        {
          type: 'category',
          label: '27th ごめんね Fingers crossed',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/27/gomennefingerscrossed'
          ]
        },
        {
          type: 'category',
          label: '26th 僕は僕を好きになる',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/26/bokuwabokuosukininaru',
            'singles/26/wilderness-world'
          ]
        },
        {
          type: 'category',
          label: '25th しあわせの保護色',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/25/shiawasenohogoshoku'
          ]
        },
        {
          type: 'category',
          label: '24th 夜明けまで強がらなくてもいい',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/24/yoakemadetsuyogaranakutemoii'
          ]
        },
        {
          type: 'category',
          label: '23rd Sing Out',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/23/sing-out',
            'singles/23/23-4banmenohikari'
          ]
        },
        {
          type: 'category',
          label: '22nd 帰り道は遠回りしたくなる',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/22/kaerimichiwatomawarishitakunaru'
          ]
        },

        {
          type: 'category',
          label: '21st ジコチューで行こう',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/21/jikochudeikou'
          ]
        },
        {
          type: 'category',
          label: '20rd シンクロニシティ',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/20/synchronicity'
          ]
        },
        {
          type: 'category',
          label: '19th いつかできるから今日できる',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/19/itsukadekirukarakyoudekiru'
          ]
        },


        {
          type: 'category',
          label: '18th 逃げ水',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/18/mirage'
          ]
        },


        {
          type: 'category',
          label: '17th インフルエンサー',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/17/influencer',
            'singles/17/sanbanmenokaze'
          ]
        },




        {
          type: 'category',
          label: '16th サヨナラの意味',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/16/sayonaranoimi'
          ]
        },
        {
          type: 'category',
          label: '15th 裸足でSummer',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/15/hadashidesummer'
          ]
        },

        {
          type: 'category',
          label: '14th ハルジオンが咲く頃',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/14/harujiongasakukoro'
          ]
        },
        {
          type: 'category',
          label: '13th 今、話したい誰かがいる',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/13/imahanashitaidarekagairu'
          ]
        },
        {
          type: 'category',
          label: '12th 太陽ノック',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/12/taiyouknock'
          ]
        },
        {
          type: 'category',
          label: '11th 命は美しい',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/11/inochiwautsukushii'
          ]
        },


        {
          type: 'category',
          label: '10th 何度目の青空か?',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/10/nandomenoaozoraka'
          ]
        },
        {
          type: 'category',
          label: '9th 夏のFree&Easy',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/9/natsunofreeandeasy'
          ]
        },

        {
          type: 'category',
          label: '8th 気づいたら片想い',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/8/kizuitarakataomoi',
            'singles/8/dankeschon'
          ]
        },
        {
          type: 'category',
          label: '7th バレッタ',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/7/barrette'
          ]
        },

        {
          type: 'category',
          label: '6th ガールズルール',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/6/girls-rule'
          ]
        },
        {
          type: 'category',
          label: '5th 君の名は希望',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/5/kiminonawakibou',
            'singles/5/romanticikayaki'
          ]
        },


        {
          type: 'category',
          label: '4th 制服のマネキン',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/4/seifukunomannequin'
          ]
        },
        {
          type: 'category',
          label: '3rd 走れ!Bicycle',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/3/hashirebicycle'
          ]
        },
        {
          type: 'category',
          label: '2nd おいでシャンプー',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/2/guuzenwoliwakanishite',
            'singles/2/house',
            'singles/2/oideshampoo'
          ]
        },
        {
          type: 'category',
          label: '1st ぐるぐるカーテン',
          link: {
            'type': 'generated-index',
          },
          items: [
            'singles/1/gurugurucurtain'
          ]
        },
      ]
    },
  ]
};

export default sidebars;
